import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/portal.js';import {hash,verify,url} from '../server/security.mjs';
const uid='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test';
function response(){return {statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;},redirect(n,v){this.statusCode=n;this.location=v;}};}
async function call(action,body,user={id:uid,name:'Técnico',username:'tecnico',is_admin:false},item){const calls=[];const real=global.fetch;global.fetch=async(u,init)=>{calls.push({u,init});let data=[];if(u.includes('portal_sessions?'))data=[{user_id:uid}];else if(u.includes('portal_users?id='))data=[user];else if(u.includes('portal_items?'))data=item?[item]:[];else if(u.includes('portal_settings?'))data=[{current_tax:null}];return {ok:true,status:200,json:async()=>data};};const res=response();try{await handler({url:'/api/portal?action='+action,method:body?'POST':'GET',headers:{host:'localhost',cookie:'session='+'a'.repeat(64)},body},res);}finally{global.fetch=real;}return {res,calls};}
test('Passwords are salted hashes and validate correctly',()=>{const h=hash('123');assert.notEqual(h,hash('123'));assert(verify('123',h));assert(!verify('wrong',h));});
test('Unsafe links rejected',()=>{assert.throws(()=>url('javascript:alert(1)'));assert.equal(url('https://example.com'),'https://example.com/');});
test('No session cannot read data',async()=>{const r=response();await handler({url:'/api/portal',method:'GET',headers:{}},r);assert.equal(r.statusCode,401);});
test('Notes query includes owner restriction',async()=>{const {calls}=await call('state');assert(calls.some(c=>c.u.includes('or=(kind.neq.notes,owner_id.eq.'+uid+')')));});
test('Regular technician cannot create users',async()=>{const {res,calls}=await call('user-save',{name:'X',username:'xx',password:'123'});assert.equal(res.statusCode,403);assert(!calls.some(c=>c.init.method==='POST'));});
test('Notes belonging to another user cannot be modified',async()=>{const {res}=await call('save',{id:other,kind:'notes',title:'attack'},undefined,{id:other,kind:'notes',owner_id:other});assert.equal(res.statusCode,404);});
test('Notes belonging to another user cannot be deleted',async()=>{const {res,calls}=await call('delete',{id:other},undefined,{id:other,kind:'notes',owner_id:other});assert.equal(res.statusCode,404);assert(!calls.some(c=>c.init.method==='DELETE'));});
test('Uploaded paths cannot be assigned by another owner',async()=>{const {res}=await call('save',{kind:'files',title:'file',file_path:other+'/file'});assert.equal(res.statusCode,403);});
test('Initial administrators cannot be deleted',async()=>{const {res}=await call('user-delete',{id:uid},{id:uid,name:'Vitor',username:'vitor',is_admin:true});assert.equal(res.statusCode,400);});
test('A foreign origin cannot submit changes',async()=>{const r=response();await handler({url:'/api/portal?action=save',method:'POST',headers:{origin:'https://evil.example',host:'localhost'},body:{}},r);assert.equal(r.statusCode,403);});
